PROJECT_NAME := simulator_writer

TOP     := tl_simulator_writer
TB_TOP  := tb_simulator_writer

SRC_FILES := tl_simulator_writer.vhd
TB_FILES  := test/tb_simulator_writer.vhd

VHDL_STANDARD := 08

include ../mk/common.mk
