PROJECT_NAME := simulator_writer

TOP     := tl_simulator_writer
TB_TOP  := tb_simulator_writer

SRC_FILES := tl_simulator_writer.vhd
TB_FILES  := test/tb_simulator_writer.vhd

VHDL_STANDARD := 08

# Verilog mirror.
V_TOP       := tl_simulator_writer
V_TB_TOP    := tb_simulator_writer
V_SRC_FILES := tl_simulator_writer.v
V_TB_FILES  := test/tb_simulator_writer.v

include ../mk/common.mk
