PROJECT_NAME := forwarding_unit

TOP     := forwarding_unit
TB_TOPS := tb_forwarding_unit

SRC_FILES := forwarding_unit.vhd
TB_FILES  := test/tb_forwarding_unit.vhd

VHDL_STANDARD := 08

V_TOP       := forwarding_unit
V_TB_TOPS   := tb_forwarding_unit
V_SRC_FILES := forwarding_unit.v
V_TB_FILES  := test/tb_forwarding_unit.v

include ../../../mk/common.mk
