PROJECT_NAME := fir4tap

TOP     := fir4tap
TB_TOPS := tb_fir4tap

SRC_FILES := fir4tap.vhd
TB_FILES  := test/tb_fir4tap.vhd

VHDL_STANDARD := 08

V_TOP       := fir4tap
V_TB_TOPS   := tb_fir4tap
V_SRC_FILES := fir4tap.v
V_TB_FILES  := test/tb_fir4tap.v

include ../../../mk/common.mk
