PROJECT_NAME := fifo_sync

TOP     := fifo_sync
TB_TOP  := tb_fifo_sync

SRC_FILES := fifo_sync.vhd
TB_FILES  := test/tb_fifo_sync.vhd

VHDL_STANDARD := 08

V_TOP       := fifo_sync
V_TB_TOP    := tb_fifo_sync
V_SRC_FILES := fifo_sync.v
V_TB_FILES  := test/tb_fifo_sync.v

include ../mk/common.mk
