PROJECT_NAME := mode_blink

TOP     := mode_blink
TB_TOPS := tb_mode_blink

SRC_FILES := mode_blink.vhd
TB_FILES  := test/tb_mode_blink.vhd

VHDL_STANDARD := 08

V_TOP       := mode_blink
V_TB_TOPS   := tb_mode_blink
V_SRC_FILES := mode_blink.v
V_TB_FILES  := test/tb_mode_blink.v

include ../../mk/common.mk
