PROJECT_NAME := pwm_led

TOP     := pwm_led
TB_TOP  := tb_pwm_led

SRC_FILES := pwm_led.vhd
TB_FILES  := test/tb_pwm_led.vhd

VHDL_STANDARD := 08

V_TOP       := pwm_led
V_TB_TOP    := tb_pwm_led
V_SRC_FILES := pwm_led.v
V_TB_FILES  := test/tb_pwm_led.v

include ../mk/common.mk
