PROJECT_NAME := simd_alu

TOP     := simd_alu
TB_TOPS := tb_simd_alu

SRC_FILES := simd_alu.vhd
TB_FILES  := test/tb_simd_alu.vhd

VHDL_STANDARD := 08

V_TOP       := simd_alu
V_TB_TOPS   := tb_simd_alu
V_SRC_FILES := simd_alu.v
V_TB_FILES  := test/tb_simd_alu.v

include ../../../mk/common.mk
