PROJECT_NAME := debounce

TOP     := Debounce
TB_TOPS := tb_debounce_bounce tb_debounce_glitch

SRC_FILES := Debounce.vhd
TB_FILES  := test/tb_debounce_bounce.vhd test/tb_debounce_glitch.vhd

VHDL_STANDARD := 08

V_TOP       := Debounce
V_TB_TOPS   := tb_debounce_bounce tb_debounce_glitch
V_SRC_FILES := Debounce.v
V_TB_FILES  := test/tb_debounce_bounce.v test/tb_debounce_glitch.v

include ../../mk/common.mk
