PROJECT_NAME := shift_register

TOP     := shift_register
TB_TOPS := tb_shift_register

SRC_FILES := shift_register.vhd
TB_FILES  := test/tb_shift_register.vhd

VHDL_STANDARD := 08

V_TOP       := shift_register
V_TB_TOPS   := tb_shift_register
V_SRC_FILES := shift_register.v
V_TB_FILES  := test/tb_shift_register.v

include ../../mk/common.mk
