PROJECT_NAME := mod_counter

TOP     := mod_counter
TB_TOPS := tb_mod_counter

SRC_FILES := mod_counter.vhd
TB_FILES  := test/tb_mod_counter.vhd

VHDL_STANDARD := 08

V_TOP       := mod_counter
V_TB_TOPS   := tb_mod_counter
V_SRC_FILES := mod_counter.v
V_TB_FILES  := test/tb_mod_counter.v

include ../../mk/common.mk
