PROJECT_NAME := clock_enable

TOP     := clock_enable
TB_TOPS := tb_clock_enable
SRC_FILES := clock_enable.vhd
TB_FILES  := test/tb_clock_enable.vhd

V_TOP       := clock_enable
V_TB_TOPS   := tb_clock_enable
V_SRC_FILES := clock_enable.v
V_TB_FILES  := test/tb_clock_enable.v

include ../../mk/common.mk
