PROJECT_NAME := ram_sync

TOP     := ram_sync
TB_TOPS := tb_ram_sync

SRC_FILES := ram_sync.vhd
TB_FILES  := test/tb_ram_sync.vhd

VHDL_STANDARD := 08

V_TOP       := ram_sync
V_TB_TOPS   := tb_ram_sync
V_SRC_FILES := ram_sync.v
V_TB_FILES  := test/tb_ram_sync.v

include ../../mk/common.mk
