PROJECT_NAME := counter_timer

TOP     := CounterTimer
TB_TOPS := tb_counter_timer

SRC_FILES := ../timer/Timer.vhd CounterTimer.vhd
TB_FILES  := test/tb_counter_timer.vhd

VHDL_STANDARD := 08

V_TOP       := CounterTimer
V_TB_TOPS   := tb_counter_timer
V_SRC_FILES := ../timer/Timer.v CounterTimer.v
V_TB_FILES  := test/tb_counter_timer.v

SVG_RELABEL    := inner_timer=Timer
V_SVG_RELABEL  := inner_timer=Timer
SVG_LINKS      := inner_timer=../building_blocks-timer/Timer.svg
V_SVG_LINKS    := inner_timer=../building_blocks-timer/Timer_v.svg

include ../../mk/common.mk
