PROJECT_NAME := counter_timer

TOP     := CounterTimer
TB_TOPS := tb_counter_timer

SRC_FILES := ../timer/Timer.vhd CounterTimer.vhd
TB_FILES  := test/tb_counter_timer.vhd

VHDL_STANDARD := 08

V_TOP       := CounterTimer
V_TB_TOPS   := tb_counter_timer
V_SRC_FILES := ../timer/Timer.v CounterTimer.v
V_TB_FILES  := test/tb_counter_timer.v

include ../../mk/common.mk
