PROJECT_NAME := uart_rx

TOP     := uart_rx
TB_TOPS := tb_uart_rx

SRC_FILES := uart_rx.vhd
TB_FILES  := test/tb_uart_rx.vhd

VHDL_STANDARD := 08

V_TOP       := uart_rx
V_TB_TOPS   := tb_uart_rx
V_SRC_FILES := uart_rx.v
V_TB_FILES  := test/tb_uart_rx.v

include ../../mk/common.mk
