PROJECT_NAME := regfile_rv32

TOP     := regfile_rv32
TB_TOPS := tb_regfile_rv32

SRC_FILES := regfile_rv32.vhd
TB_FILES  := test/tb_regfile_rv32.vhd

VHDL_STANDARD := 08

V_TOP       := regfile_rv32
V_TB_TOPS   := tb_regfile_rv32
V_SRC_FILES := regfile_rv32.v
V_TB_FILES  := test/tb_regfile_rv32.v

include ../../../mk/common.mk
