PROJECT_NAME := hazard_detector

TOP     := hazard_detector
TB_TOPS := tb_hazard_detector

SRC_FILES := hazard_detector.vhd
TB_FILES  := test/tb_hazard_detector.vhd

VHDL_STANDARD := 08

V_TOP       := hazard_detector
V_TB_TOPS   := tb_hazard_detector
V_SRC_FILES := hazard_detector.v
V_TB_FILES  := test/tb_hazard_detector.v

include ../../../mk/common.mk
