PROJECT_NAME := uart_tx

TOP     := uart_tx
TB_TOPS := tb_uart_tx

SRC_FILES := uart_tx.vhd
TB_FILES  := test/tb_uart_tx.vhd

VHDL_STANDARD := 08

V_TOP       := uart_tx
V_TB_TOPS   := tb_uart_tx
V_SRC_FILES := uart_tx.v
V_TB_FILES  := test/tb_uart_tx.v

include ../mk/common.mk
