// rom_lut_func.v - Storage method C for the ROM_LUT example.
//
// Same I/O and quadrant logic as rom_lut.v. Method C's lesson is
// "compute the cross-product table at elaboration from a much
// smaller seed table" — here the seed is a 32-entry precomputed
// fixed-point sine table, and the integer-math `compute_rom`
// function builds the full 32 × 16 LUT by multiplying by the
// nibble factor and the magnitude scale. The whole computation is
// **synthesisable**: yosys and Quartus both fold the elaboration-
// time function into a constant ROM the same way they would for
// method A's inline literal — just with the bulk of the data
// derived from 32 numbers instead of 512.
//
// The bit-exact equivalence to methods A and B is preserved: the
// SIN_FIXED constants below were generated by a one-line Python
//
//     [round(math.sin(a * math.pi / 64) * 32768) for a in range(32)]
//
// then the per-entry computation is
//
//     rom(a, n) = (SIN_FIXED[a] * n * 31 + 16384) >> 15
//
// which matches the Python `round(sin(a * pi/64) * n * 31)` used by
// generate_tables.py (the source of the .hex method-B uses) for
// every (angle, nibble) pair.

module rom_lut_func #(
    parameter integer ARRAY_SIZE          = 32,
    parameter integer ELEMENTS_BITS_COUNT = 9
) (
    input  wire                          clock,
    input  wire [6:0]                    read_angle_idx,
    input  wire [3:0]                    nibble_product_idx,
    output reg  [ELEMENTS_BITS_COUNT:0]  data_out
);

    // Q15 fixed-point sine table: SIN_FIXED[a] = round(sin(a · π / 64) · 2^15).
    // 32 entries covering 0..π/2; the upper quadrants are mirrored
    // by the read-side logic below.
    function automatic integer sin_fixed_q15(input integer a);
        case (a)
             0: sin_fixed_q15 =     0;     1: sin_fixed_q15 =  1608;
             2: sin_fixed_q15 =  3212;     3: sin_fixed_q15 =  4808;
             4: sin_fixed_q15 =  6393;     5: sin_fixed_q15 =  7962;
             6: sin_fixed_q15 =  9512;     7: sin_fixed_q15 = 11039;
             8: sin_fixed_q15 = 12540;     9: sin_fixed_q15 = 14010;
            10: sin_fixed_q15 = 15446;    11: sin_fixed_q15 = 16846;
            12: sin_fixed_q15 = 18204;    13: sin_fixed_q15 = 19519;
            14: sin_fixed_q15 = 20787;    15: sin_fixed_q15 = 22005;
            16: sin_fixed_q15 = 23170;    17: sin_fixed_q15 = 24279;
            18: sin_fixed_q15 = 25330;    19: sin_fixed_q15 = 26319;
            20: sin_fixed_q15 = 27245;    21: sin_fixed_q15 = 28106;
            22: sin_fixed_q15 = 28898;    23: sin_fixed_q15 = 29621;
            24: sin_fixed_q15 = 30273;    25: sin_fixed_q15 = 30853;
            26: sin_fixed_q15 = 31357;    27: sin_fixed_q15 = 31785;
            28: sin_fixed_q15 = 32138;    29: sin_fixed_q15 = 32413;
            30: sin_fixed_q15 = 32610;    31: sin_fixed_q15 = 32729;
            default: sin_fixed_q15 = 0;
        endcase
    endfunction

    // Build the full ROM at elaboration. All inputs and intermediate
    // values are `integer` — pure synthesisable integer math.
    function automatic [ELEMENTS_BITS_COUNT-1:0] compute_entry(
        input integer row,
        input integer col
    );
        integer prod;
        begin
            // round( sin(row · π/64) · col · 31 )
            //   = ( SIN_FIXED[row] · col · 31 + 2^14 ) >>> 15
            prod = sin_fixed_q15(row) * col * 31 + 16384;
            compute_entry = prod >>> 15;
        end
    endfunction

    reg [ELEMENTS_BITS_COUNT-1:0] rom [0:ARRAY_SIZE*16-1];

    integer row, col;
    initial begin
        for (row = 0; row < ARRAY_SIZE; row = row + 1) begin
            for (col = 0; col < 16; col = col + 1) begin
                rom[row*16 + col] = compute_entry(row, col);
            end
        end
    end

    wire        secondOrFourthQuadrant  = read_angle_idx[5];
    wire        thirdOrFourthQuadrant   = read_angle_idx[6];
    wire [4:0]  firstQuadrantTableIndex = read_angle_idx[4:0];

    reg  [4:0]  tableOfTablesIdx;
    reg  [ELEMENTS_BITS_COUNT-1:0] rom_value;

    always @(posedge clock) begin
        if (secondOrFourthQuadrant)
            tableOfTablesIdx = 5'd31 - firstQuadrantTableIndex;
        else
            tableOfTablesIdx = firstQuadrantTableIndex;

        rom_value = rom[{tableOfTablesIdx, nibble_product_idx}];

        if (thirdOrFourthQuadrant)
            data_out <= -{1'b0, rom_value};
        else
            data_out <= {1'b0, rom_value};
    end

endmodule
