#!/usr/bin/env python3
# generate_sincos_lut.py
#
# Regenerates `sincos_lut.hex`, the 16384-entry signed-16-bit sine
# table consumed by the Verilog mirror via $readmemh. The same data
# is also baked inline into `sincos_lut.vhd` (one-time generation —
# the VHDL file is checked in, not generated by CI).
#
# Formula:
#   entry[i] = round(sin(2*pi*i / 16384) * 32767)   for i in 0..16383
# stored as 4-hex-digit two's complement.
#
# Run from the project directory:
#   podman run --rm -v "$PWD":/work:rw -w /work \
#       ghcr.io/naelolaiz/hdltools:release \
#       python3 generate_sincos_lut.py

import math
import os
import sys

ENTRIES = 16384
SCALE = 32767
OUT = os.path.join(os.path.dirname(__file__) or ".", "sincos_lut.hex")


def main() -> int:
    with open(OUT, "w") as fh:
        fh.write("// sincos_lut.hex - 16384 entries of 16-bit signed sine.\n")
        fh.write(f"// entry[i] = round(sin(2*pi*i / {ENTRIES}) * {SCALE})\n")
        fh.write("// Two's complement, 4 hex digits per entry. Loaded via\n")
        fh.write("// $readmemh in `sincos_lut.v`. Mirrors the inline-literal\n")
        fh.write("// table in `sincos_lut.vhd`; both must agree bit-for-bit.\n")
        for i in range(ENTRIES):
            v = round(math.sin(2.0 * math.pi * i / ENTRIES) * SCALE)
            fh.write(f"{v & 0xFFFF:04x}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
