PROJECT_NAME := alu_rv32

TOP     := alu_rv32
TB_TOPS := tb_alu_rv32

SRC_FILES := alu_rv32.vhd
TB_FILES  := test/tb_alu_rv32.vhd

VHDL_STANDARD := 08

V_TOP       := alu_rv32
V_TB_TOPS   := tb_alu_rv32
V_SRC_FILES := alu_rv32.v
V_TB_FILES  := test/tb_alu_rv32.v

include ../../../mk/common.mk
