PROJECT_NAME := fifo_sync

TOP     := fifo_sync
TB_TOPS := tb_fifo_sync tb_fifo_sync_overlapping

SRC_FILES := fifo_sync.vhd
TB_FILES  := test/tb_fifo_sync.vhd test/tb_fifo_sync_overlapping.vhd

VHDL_STANDARD := 08

V_TOP       := fifo_sync
V_TB_TOPS   := tb_fifo_sync tb_fifo_sync_overlapping
V_SRC_FILES := fifo_sync.v
V_TB_FILES  := test/tb_fifo_sync.v test/tb_fifo_sync_overlapping.v

include ../../mk/common.mk
