PROJECT_NAME := 7segments_counter

# NOTE: the top entity is still called `test` because the source file is
# `test.vhd`. The project README flags this as a rename TODO; once
# renamed, update `TOP` and the file names in SRC_FILES below.
TOP     := test
TB_TOP  := tb_test

SRC_FILES := test.vhd
TB_FILES  := test/tb_test.vhd

VHDL_STANDARD := 08

include ../../mk/common.mk
