PROJECT_NAME := 7segments_counter

# NOTE: the top entity is still called `test` because the source file is
# `test.vhd`. The project README flags this as a rename TODO; once
# renamed, update `TOP` and the file names in SRC_FILES below.
TOP     := test
TB_TOP  := tb_test

SRC_FILES := test.vhd
TB_FILES  := test/tb_test.vhd

VHDL_STANDARD := 08

# Verilog mirror.
V_TOP       := test
V_TB_TOP    := tb_test
V_SRC_FILES := test.v
V_TB_FILES  := test/tb_test.v

include ../../mk/common.mk
