PROJECT_NAME := variable_timer

TOP     := VariableTimer
TB_TOPS := tb_variable_timer

SRC_FILES := ../timer/Timer.vhd VariableTimer.vhd
TB_FILES  := test/tb_variable_timer.vhd

VHDL_STANDARD := 08

V_TOP       := VariableTimer
V_TB_TOPS   := tb_variable_timer
V_SRC_FILES := ../timer/Timer.v VariableTimer.v
V_TB_FILES  := test/tb_variable_timer.v

SVG_RELABEL    := inner=Timer
V_SVG_RELABEL  := inner=Timer
SVG_LINKS      := inner=../building_blocks-timer/Timer.svg
V_SVG_LINKS    := inner=../building_blocks-timer/Timer_v.svg

include ../../mk/common.mk
