# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        backend: [ '', mcode, llvm, gcc ]
        version: [ 20.04, latest ]
        #version: [ 18.04, 20.04, latest ] # TODO: put 18.04 back commenting screenshots generation on it
    runs-on: ubuntu-${{ matrix.version }}
    name: '🐧 Ubuntu ${{ matrix.version }} · ${{ matrix.backend }}'

    container:
      image: ghcr.io/naelolaiz/hdltools:release
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      volumes:
        - src:/src
        - generated_images:/generated_images

    steps:
    #- name: create output dir for images
    #  run: mkdir generated_images
      
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: test_blink_led
      run: |
        ghdl --version
        cd blink_led
        ghdl -a blink_led.vhd
        ghdl -e blink_led
        ./blink_led --assert-level=error

    - name: test_serial2parallel
      run: |
        echo "GHDL_PREFIX: ghdl_PREFIX"
        echo "GHDL: ghdl"
        echo "GHDL_LIBS: ghdl_LIBS"
        ghdl --version
        cd general_components/
        ghdl -a Serial2Parallel.vhd
        ghdl -a Serial2Parallel_tb.vhd
        ghdl -e serial2parallel_tb
        ghdl -r serial2parallel_tb --assert-level=error --vcd=serial2parallel_tb.vcd
        python3 /tools/vcd2png.py serial2parallel_tb.vcd
        mv gtkwave_serial2parallel_tb.png /generated_images/
        
    - name: test_7segments_counter
      run: |
        echo "GHDL_PREFIX: ghdl_PREFIX"
        echo "GHDL: ghdl"
        echo "GHDL_LIBS: ghdl_LIBS"
        ghdl --version
        cd 7segments/counter/test
        ghdl -a ../test.vhd
        ghdl -a tb_test.vhd
        ghdl -e tb_test
        ghdl -r tb_test --assert-level=error --vcd=7segments_counter_tb.vcd
        python3 /tools/vcd2png.py 7segments_counter_tb.vcd
        mv gtkwave_7segments_counter_tb.png /generated_images/
        cd ..
        /tools/vhd2svg.sh $(pwd)/test.vhd /generated_images/7_segments_counter_toplevel_diagram.svg

    - uses: actions/upload-artifact@v3
      with:
        name: screenshots  ${{ matrix.version }}·${{ matrix.backend }}
        path: /generated_images
